## Machine Learning Pipeline

As the class practice, the students will be required to develop a machine learning pipeline using the `Churn_Modelling_train_test.csv` dataset.

**About dataset**

This dataset is obained from [kaggle](https://www.kaggle.com/datasets/shubhammeshram579/bank-customer-churn-prediction?resource=download). It contains information on bank customers who either left the bank or continue to be a customer. The dataset includes the following attributes:

* Customer ID: A unique identifier for each customer
* Surname: The customer's surname or last name
* Credit Score: A numerical value representing the customer's credit score
* Geography: The country where the customer resides (France, Spain or Germany)
* Gender: The customer's gender (Male or Female)
* Age: The customer's age.
* Tenure: The number of years the customer has been with the bank
* Balance: The customer's account balance
* NumOfProducts: The number of bank products the customer uses (e.g., savings account, credit card)
* HasCrCard: Whether the customer has a credit card (1 = yes, 0 = no)
* IsActiveMember: Whether the customer is an active member (1 = yes, 0 = no)
* EstimatedSalary: The estimated salary of the customer
* Exited: Whether the customer has churned (1 = yes, 0 = no)

### Exploratory Data Analysis

In this section the students are required to do an EDA to understand the dataset.

In [1]:
# import packages
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import f1_score
import mlflow
import mlflow
from mlflow.models import infer_signature

c:\Users\miqi\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# Load the dataset
df = pd.read_csv("C:/Users/miqi/Desktop/med-image-clarity/mlops-and-system-design1/session2/Class Exercise/Churn_Modelling_train_test.csv")

In [3]:
# dataset analysis
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          1
Gender             0
Age                1
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          1
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [4]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,9001.000000,9.001000e+03,9001.000000,9000.000000,9001.000000,9001.000000,9001.000000,9000.000000,9001.000000,9001.000000,9001.000000
mean,5003.366515,1.569072e+07,650.681369,38.901781,5.007888,76222.210827,1.531497,0.705667,0.514721,100180.823967,0.204422
std,2884.787499,7.179353e+04,96.539591,10.450760,2.894025,62432.198151,0.579398,0.455768,0.499811,57561.189534,0.403301
min,2.000000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.000000,0.000000,11.580000,0.000000
25%,2509.000000,1.562811e+07,584.000000,32.000000,2.000000,0.000000,1.000000,0.000000,0.000000,50972.600000,0.000000
50%,4989.000000,1.569096e+07,652.000000,37.000000,5.000000,96997.090000,1.000000,1.000000,1.000000,100556.980000,0.000000
75%,7505.000000,1.575265e+07,718.000000,44.000000,7.000000,127450.140000,2.000000,1.000000,1.000000,149458.730000,0.000000
max,10000.000000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.000000,1.000000,199992.480000,1.000000

In [5]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                float64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard          float64
IsActiveMember     float64
EstimatedSalary    float64
Exited               int64
dtype: object

In [6]:
# review categorical variables
categorical_variables = df.select_dtypes(include="object").columns

for col in categorical_variables:
    print(df[col].value_counts())

Surname
Smith       29
Martin      25
Yeh         25
Walker      24
Genovese    23
            ..
Lappin       1
Pettit       1
Combes       1
Foxall       1
Webster      1
Name: count, Length: 2772, dtype: int64
Geography
France     4505
Spain      2250
Germany    2245
Name: count, dtype: int64
Gender
Male      4906
Female    4095
Name: count, dtype: int64

In [7]:
# review binary variables
df[['HasCrCard', 'IsActiveMember', 'Exited']] = df[['HasCrCard', 'IsActiveMember', 'Exited']].fillna(0).astype(int)

df['Gender'] = df['Gender'].map({'Female': 1, 'Male': 0})

binary_variables = ['HasCrCard', 'IsActiveMember', 'Exited', 'Gender']
for col in binary_variables:
    print(df[col].value_counts())

HasCrCard
1    6351
0    2650
Name: count, dtype: int64
IsActiveMember
1    4633
0    4368
Name: count, dtype: int64
Exited
0    7161
1    1840
Name: count, dtype: int64
Gender
0    4906
1    4095
Name: count, dtype: int64

In [8]:
# review numerical variables
numerical_cols = [
    col for col in df.select_dtypes(include=["int64","float64"]).columns
    if df[col].nunique() > 2
]
df[numerical_cols].head(5)

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,EstimatedSalary
0,4784,15729224,710,37.0,5,0.00,2,115403.31
1,1497,15799156,569,38.0,8,0.00,2,79618.79
2,1958,15674922,710,54.0,6,171137.62,1,167023.95
3,9174,15653572,673,43.0,8,127132.96,1,6009.27
4,9748,15775761,610,69.0,5,86038.21,3,192743.06

**EDA Conclusions**

From this Exploratory Data Analysis we can retrieve the following information:
* *To be completed by the student*

### ML Pipeline

In this section the students are required to create a ML pipeline to predict whether the customer left the bank or not.

In [9]:
# import packages
import pandas as pd

In [10]:
# Load the dataset
df = pd.read_csv("C:/Users/miqi/Desktop/med-image-clarity/mlops-and-system-design1/session2/Class Exercise/Churn_Modelling_train_test.csv")

In [11]:
# Preprocess the features - create a function or a class for it 
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

def transform(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["Geography"] = df["Geography"].fillna(df["Geography"].mode()[0])
    df["HasCrCard"] = df["HasCrCard"].fillna(df["HasCrCard"].median())
    df['Gender'] = df['Gender'].map({'Male': 0, 'Female': 1})
    df[numerical_cols] = scaler.fit_transform(df[numerical_cols])
    return df

df = transform(df)

In [12]:
# balance the dataset (if you think it is necessary)
df["Exited"].value_counts()
drop_idx = df[df['Exited'] == 0].sample(6000, random_state=42).index
df = df.drop(drop_idx)
df['Exited'].value_counts()

Exited
1    1840
0    1161
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier

hyper_parameters = {
    "criterion": ["gini", "entropy"],
    "max_depth": [3, 5, 10, 15, None],
    "min_samples_split": [2, 5, 10],       
    "min_samples_leaf": [1, 2, 4],        
    "max_features": [None, "sqrt", "log2"],
}

grid_search_dt = RandomizedSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_distributions=hyper_parameters,
    n_iter=20,        
    cv=3,             
    scoring="f1",
    n_jobs=-1,
    random_state=42,
    verbose=1,
)

In [13]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split, GridSearchCV

y = df["Exited"]
X = df.drop(columns=["Exited", "RowNumber", "CustomerId", "Surname"])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

ct = ColumnTransformer(transformers=[
    ('encoder', OneHotEncoder(drop='first'), ['Geography'])
], remainder='passthrough')

X_train = ct.fit_transform(X_train)
X_test = ct.transform(X_test)

hyper_parameters = {
    "criterion": ["gini", "entropy"],
    "max_depth": [3, 5, 10, 15, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": [None, "sqrt", "log2"],
}

grid_search_dt = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid=hyper_parameters,
    cv=3,
    scoring="f1",
    n_jobs=-1,
    verbose=1,
)

grid_search_dt.fit(X_train, y_train)

print("Best params:", grid_search_dt.best_params_)
print(f"Best F1 (CV): {grid_search_dt.best_score_}")

params_dt = grid_search_dt.best_params_
dt = grid_search_dt.best_estimator_
y_pred_dt = dt.predict(X_test)

Fitting 3 folds for each of 270 candidates, totalling 810 fits
Best params: {'criterion': 'entropy', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'min_samples_split': 10}
Best F1 (CV): 0.7841760632913061

In [14]:
params = grid_search_dt.best_params_
lr = grid_search_dt.best_estimator_
y_pred = lr.predict(X_test)

In [15]:
from sklearn.metrics import f1_score, accuracy_score
from mlflow.models import infer_signature

mlflow.set_experiment("LR Experiment")

with mlflow.start_run():
    mlflow.log_params(params)

    f1 = f1_score(y_test, y_pred)
    acc = accuracy_score(y_test, y_pred)
    mlflow.log_metric("f1_score", f1)
    mlflow.log_metric("accuracy", acc)

    mlflow.set_tag("Training Info", "Basic LR model to present MLFlow capabilities")

    signature = infer_signature(X_train, lr.predict(X_train))

    model_info = mlflow.sklearn.log_model(
        sk_model=lr,
        artifact_path="bank_model",
        signature=signature,
        input_example=X_train,
        registered_model_name="bank-model-basic",
    )

2026/05/26 10:27:32 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/26 10:27:32 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 2011.11it/s]
Registered model 'bank-model-basic' already exists. Creating a new version of this model...
Created version '2' of model 'bank-model-basic'.

### MLFlow Integration

In this section the students are required to track the model and the parameters into MLFlow.

In [16]:
# import packages for mlfow
import mlflow

Start a local Tracking server on port 8080 - it is necessary to import mlflow and open a new terminal

In [18]:
# Set our tracking server uri for logging on port 8080
#First i have used py -m mlflow server --host 127.0.0.1 --port 8080 in my powershell
remote_Server_uri = "http://127.0.0.1:8080"
mlflow.set_tracking_uri(remote_Server_uri)
mlflow.set_experiment("/my-experiment")

<Experiment: artifact_location='mlflow-artifacts:/1', creation_time=1779177336210, experiment_id='1', last_update_time=1779177336210, lifecycle_stage='active', name='/my-experiment', tags={}, trace_location=None, workspace='default'>

Visit the MLFlow UI on `http://127.0.0.1:8080`

In [20]:
# Create a new MLflow Experiment called `Practice Experiment - {Your Name}`
import os
experiment_name = "Practice Expermient (FINAL) - {Miquel Vilà}"
experiment_id = mlflow.create_experiment(experiment_name)

In [21]:
# Define the model hyperparameters
params = {
    "solver": "lbfgs",
    "max_iter": 1000,
    "random_state": 50,
}

lr = LogisticRegression(**params)
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [22]:
# Train the model
lr = LogisticRegression(**params)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=50)

In [23]:
# Predict on the test set
y_pred = lr.predict(X_test)

In [24]:
# import libraries
import mlflow
from mlflow.models import infer_signature

In [25]:
# Set our tracking server uri for logging
mlflow.set_tracking_uri(uri="http://127.0.0.1:8080")

In [26]:
# Start an MLflow run
# Check the accuracy of the model on the `test sample`
mlflow.set_experiment("Practice Expermient FINAL - {Miquel Vilà}")

# Start an MLflow run
with mlflow.start_run():
    # Log the hyperparameters
    mlflow.log_params(params)

    # Log the loss metric
   # Calcula el valor antes de loggearlo
    f1 = f1_score(y_test, y_pred)  # o y_train según tu caso
    mlflow.log_metric("f1_score", f1)

    # Set a tag that we can use to remind ourselves what this run was for
    mlflow.set_tag("Training Info", "Basic LR model to present MLFlow capabilities")

    # Infer the model signature
    signature = infer_signature(X_train, lr.predict(X_train))

    # Log the model
    model_info = mlflow.sklearn.log_model(
        sk_model=lr,
        artifact_path="bank_model",
        signature=signature,
        input_example=X_train,
        registered_model_name="bank-model-basic",
    )

2026/05/26 10:33:56 INFO mlflow.tracking.fluent: Experiment with name 'Practice Expermient FINAL - {Miquel Vilà}' does not exist. Creating a new experiment.
2026/05/26 10:33:56 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/26 10:33:56 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 948.26it/s]
Registered model 'bank-model-basic' already exists. Creating a new version of this model...
2026/05/26 10:34:05 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: bank-model-basic, version 4

🏃 View run rare-skunk-997 at: http://127.0.0.1:8080/#/experiments/11/runs/ff74216652ec4a73ae3379fa1ad22529
🧪 View experiment at: http://127.0.0.1:8080/#/experiments/11

Created version '4' of model 'bank-model-basic'.

### Keep practicing

In [ ]:
# Create a new experiment using other models or different parameters
...